### ISSUE TITLE
Greate Work!

### ISSUE THREAD

**Issue by atomishcv** [WHU-USI3DV/FreeReg#1]
Thank you for sharing the work. I have temporarily reproduced demo.py, but it takes up more GPU. I will try to use it to register my own dataset

**Comment by atomishcv** [comment]
Could you please explain the meaning of some parameters in demo.yaml?
  rgb_size: [1296,968]  
  dpt_size: [640,480]  ##Is this the size of the point cloud to depth map? Is it fixed?
  rgb_intrinsic: [[1163.45,0,635.626],[0,1164.79,481.600],[0,0,1]]  ##Is this the coordinate of the camera?
  dpt_intrinsic: [[574.541,0,322.522],[0,577.584,238.559],[0,0,1]]  ##Is this the coordinate of the points
My dataset only contains corresponding point clouds and images

**Comment by HpWang-whu** [comment]
Hi @atomishcv,
Thanks for your interest!
Yes, rgb_size and rgb_intrinsic are the size and intrinsic matrix of the RGB image.
Dpt_size and dpt_intrinsic are the pre-defined size and intrinsic matrix for the depth map projection of point clouds.  They are not fixed and you can set them according to your needs/data. Or you can simply use the same size and intrinsic matrix as RGB images. 
Best,

**Comment by atomishcv** [comment]
thank you very much!
