### ISSUE TITLE
https://huggingface.co/runwayml/stable-diffusion-v1-5 404

### ISSUE THREAD

**Issue by wyclike** [WHU-USI3DV/FreeReg#11]
请问谁有保留这个ckpt吗，huggingface上这个模型权重被撤了

**Comment by CaiSir0075** [comment]
+1，同样的需求

**Comment by leejngmn** [comment]
> 请问谁有保留这个ckpt吗，huggingface上这个模型权重被撤了
> +1，同样的需求

You can download it here!
https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/tree/main

**Comment by HpWang-whu** [comment]
Many thanks for your help! @leejngmn
