### ISSUE TITLE
cuda of memory

### ISSUE THREAD

**Issue by cnu-Dawn** [WHU-USI3DV/FreeReg#13]
How to solve the cuda of memory?

**Comment by HpWang-whu** [comment]
Hi @LoveMYChen ,
Sorry for the late reply!
Your might check this [issue](https://github.com/WHU-USI3DV/FreeReg/issues/5) for using FreeReg with 12G cuda memory.
Or use the lightweight version of FreeReg [Here](https://github.com/WHU-USI3DV/FreeReg/tree/FFreeReg)!

Yours,

Yours,
