### ISSUE TITLE
I download three datasets provided by datasets.But I failed to run run.py successfully 

### ISSUE THREAD

**Issue by fhjfjhgj** [WHU-USI3DV/FreeReg#15]

**Comment by cnu-Dawn** [comment]
Dataset: scannet
Source feature: ['rgb_df', 'rgb_gf']
Target feature: ['dpt_df', 'dpt_gf']
Feature weight: [1, 1]
SE(3) Solver: se3
Feature matching ratio at ir_thres 0.3: nan
Inlier ratio at ir_thres 0.3: nan
Inlier number at ir_thres 0.3: nan
Average rotation error: nan; Average translation error: nan
On successful pairs: Average rotation error: nan; Average translation error: nan
Registration recall at r_thres 20 and t_thres 0.5: nan

This is my result. Do you have the same problem！！！

**Comment by fhjfjhgj** [comment]
yes,and I am confused about it.

**Comment by fhjfjhgj** [comment]
@LoveMYChen yes and I am confused about it

**Comment by cnu-Dawn** [comment]
> @LoveMYChen是的，我对此感到困惑

Have you solved it?

**Comment by HpWang-whu** [comment]
Hi @fhjfjhgj and @LoveMYChen ,
Sorry for the late reply!
I have corrected some errors, you might need to re-pull the repo for update.
Also, I have open-sourced a easy-to-use version of FreeReg [Here](https://github.com/WHU-USI3DV/FreeReg/tree/FFreeReg). Welcome to use it!

Yours,
