### ISSUE TITLE
下载了midas但是FileNotFoundError: [Errno 2] No such file or directory: '/mnt/proj/SOTAs/ZoeDepth-main/pkgs/intel-isl_MiDaS_master/hubconf.py'

### ISSUE THREAD

**Issue by Kanna-nnn** [WHU-USI3DV/FreeReg#16]

**Comment by yanrunming** [comment]
In my case, at the end of  FreeReg/tools/zoe/zoedepth/models/base_models/midas.py
change the path
from
/mnt/proj/SOTAs/ZoeDepth-main/pkgs/intel-isl_MiDaS_master
-->
/root/.cache/torch/hub
