### ISSUE TITLE
Error loading PCA feature file './tale_features/demo/feat_pca/rgb_df-dpt_df/0-1.pth': [Errno 2] No such file or directory: './tale_features/demo/feat_pca/rgb_df-dpt_df/0-1.pth'   0%|                                                                                                | 0/1 [00:00<?, ?it/s]

### ISSUE THREAD

**Issue by Kanna-nnn** [WHU-USI3DV/FreeReg#19]
这个问题是由于什么导致的，有好心人指导一下吗

**Comment by HpWang-whu** [comment]
Hi @Kanna-nnn,
您好 这个需要检查一下这个文件是否生成 是否存在 需要看一下pipeline/gen_match.py/feature_pca_and_aggregate函数的执行情况，在里面加一些print看一下中间过程 看看有没有生成文件 生成去哪里这样。

另外，我纠正了一些代码bug能够解决您之前提出的issue，还开源了一个新的[brench](https://github.com/WHU-USI3DV/FreeReg/tree/FFreeReg)更加容易使用，欢迎尝试！

**Comment by Kanna-nnn** [comment]
> Hi @Kanna-nnn, 您好 这个需要检查一下这个文件是否生成 是否存在 需要看一下pipeline/gen_match.py/feature_pca_and_aggregate函数的执行情况，在里面加一些print看一下中间过程 看看有没有生成文件 生成去哪里这样。
> 
> 另外，我纠正了一些代码bug能够解决您之前提出的issue，还开源了一个新的[brench](https://github.com/WHU-USI3DV/FreeReg/tree/FFreeReg)更加容易使用，欢迎尝试！

感谢您的解答！
