### ISSUE TITLE
Operational issues

### ISSUE THREAD

**Issue by cnu-Dawn** [WHU-USI3DV/FreeReg#20]
Hello, I tried to run a complete data source using my own data, but the results were not very satisfactory
I only modified the data source and internal/external parameters, as well as the image size, in demo. py. Is there anything else I missed that needs to be modified?

**Comment by HpWang-whu** [comment]
Hi @LoveMYChen ,
I have fixed some issues in FFreeReg and you might re-pull and re-try it.
In FFreeReg , we use YOHO for alignment, which performs better than FCGF but is only trained on indoor data and might fail on data with large domain gaps.

Yours,

**Comment by cnu-Dawn** [comment]
Are you saying that the estimated pose is not accurate enough on outdoor data or a set of data with a very large relative attitude deviation

**Comment by HpWang-whu** [comment]
The performance may be slightly worse compared to indoor scenarios, but you can still give it a try. An example is [here](https://github.com/WHU-USI3DV/FreeReg/issues/12).
