### ISSUE TITLE
the number of keypoints for matching

### ISSUE THREAD

**Issue by KN-Zhang** [WHU-USI3DV/FreeReg#3]
The work is inspiring.

_Note that we uniformly sample a dense grid of keypoints on both the depth map and the image._

So how many points are sampled for matching?

**Comment by HpWang-whu** [comment]
Hi @KN-Zhang ,
Thanks for your interest!
we sample 32\*44 = 1408 points for indoor data and 32\*80 = 2560 points for outdoor data.

Yours,

**Comment by KN-Zhang** [comment]
Hi! What's the difference between *.color.gtd.png and *.depth.gtd.png in ScanNet? Maybe the latter is the depth of the downsampled point cloud? :)) 

And, may I ask the difference between *.depth.gtd.png and *.depth.png?

**Comment by HpWang-whu** [comment]
Hi @KN-Zhang, 
*.depth.png is the depth map projected from the sparse (down-sampled) point cloud and used for registration.
*.color.gtd.png and *.depth.gtd.png are the ground truth dense depth maps (projected from a dense point cloud) corresponding to the *.color.png and *.depth.png for correspondence evaluation.

Yours,

**Comment by KN-Zhang** [comment]
> Hi @KN-Zhang, *.depth.png is the depth map projected from the sparse (down-sampled) point cloud and used for registration. *.color.gtd.png and *.depth.gtd.png are the ground truth dense depth maps (projected from a dense point cloud) corresponding to the *.color.png and *.depth.png for correspondence evaluation.
> 
> Yours,

Thanks for your patient response. 👍
