### ISSUE TITLE
Request for the model.

### ISSUE THREAD

**Issue by HBinLi** [WHU-USI3DV/FreeReg#4]
I have some issues in loading the local model as follows. Since the MiDaS repository is also downloaded from the Internet. However, in this case, unsuccessful Internet access does not result in an error. Could you please send me a copy of it?
`        midas = torch.hub.load("/mnt/proj/SOTAs/ZoeDepth-main/pkgs/intel-isl_MiDaS_master", midas_model_type,
                                pretrained=use_pretrained_midas, source='local') `

**Comment by hjh530** [comment]
how to solve it？ or can you give me one ，thanks！
