### ISSUE TITLE
How did you set the dpt_intrinsic for a new pair?

### ISSUE THREAD

**Issue by jeremycp3** [WHU-USI3DV/FreeReg#7]
I noticed the dpt_intrinsic of the demo is [[574.541,0,322.522],[0,577.584,238.559],[0,0,1]]. But for a new pair, how should we set this value?

**Comment by HpWang-whu** [comment]
Hi @jeremycp3,
You can just set it to the same one as rgb intrinsic or some other manually defined intrinsic like https://github.com/baegwangbin/DSINE/blob/b320a9a1cc1ec23b28b227c3abdb07a5cf2ac271/utils/projection.py#L89

Yours,
